[profile.default]
src = "LimitOrderProtocol"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Compiler settings
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true

# RPC URLs
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
etherlink = "${ETHERLINK_TESTNET_RPC_URL}"
ethereum = "${ETHEREUM_RPC_URL}"

# Etherscan API keys for verification
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# Gas settings
[profile.etherlink]
gas_price = 1000000000  # 1 gwei
gas_limit = 5000000

[profile.sepolia]
gas_price = 20000000000  # 20 gwei
gas_limit = 6000000